apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL
            value: postgres://{{repl ConfigOption "database_user"}}:{{repl ConfigOption "database_password"}}@db.{{repl Namespace}}.svc.cluster.local:5432/db
        command:
        - echo "Test" >> /tmp/daaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiissssssssssssssssssssssstttttttttttttttttteiiiiiinteeeeeeest" && rm -f /tmp/daaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiissssssssssssssssssssssstttttttttttttttttteiiiiiinteeeeeeest"
